### ISSUE TITLE
Datatips not available and autocomplete does not seem to work

### ISSUE THREAD

**Issue by mm-tfx** [halohalospecial/atom-elmjutsu#125]
Hi,

Some of these great features offered by elmjutsu unfortunately stopped working for me.
I cannot get Datatips, autocomplete works for my function but does not work for Elm packages functions.

Either I am doing something incorrect or there is something around Elm version.
I am using Atom on Windows 10 and I am still on Elm 0.18

Please help troubleshooting.

Thanks.

**Comment by halohalospecial** [comment]
Hi, can I see the `elmjutsu` section of your `~/.atom/config.cson`, (where `~/.atom` is the Atom directory)?

**Comment by mm-tfx** [comment]
```
  elmjutsu:
    autocompleteSnippetsEnabled: true
    cacheDirectory: "C:\\Users\\qmarmik\\AppData\\Local\\Temp\\elmjutsu15884euDfRXbt2i1u"
    globalAutocompleteEnabled: true
    hyperclickEnabled: false
    showTypesInTooltip: true
```

I would like to mention that I am testing elm-jutsu witm Elm 0.19 and it works (really good.)
